# Numpy --Practice

In [2]:
import numpy as np

In [3]:
a=np.random.random(25).reshape([5,5])
a.ndim


2

In [4]:
np.array([[5,6],[5,6]]).ndim

2

In [5]:
a=np.arange(0,50).reshape(5,2,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [6]:
print("shape of Array",a.shape)
print("dimention of Array",a.ndim)
print("Data type of Array",a.dtype)
print("size of Array",a.size)

shape of Array (5, 2, 5)
dimention of Array 3
Data type of Array int32
size of Array 50


# Create a Basic Array

In [8]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.empty([2,3]) #random Values that can May vary

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.ones([3,5],dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

# Add, Remove, Short

In [32]:
s=np.array([4,6,8,9,0,2,33,77,999])
np.sort(s)

array([  0,   2,   4,   6,   8,   9,  33,  77, 999])

In [44]:
d=np.random.randint(0,23,[3,2,4])
d

array([[[ 7,  4,  2, 12],
        [10,  5, 11,  5]],

       [[ 0,  7, 15,  8],
        [ 8,  8, 18,  4]],

       [[19,  7, 21,  1],
        [14,  0,  1, 21]]])

In [60]:
a=np.array([1,2,3,5,7,8])
print(a)
a1=a[np.newaxis,:]
a1.shape #row dimensional extension

[1 2 3 5 7 8]


(1, 6)

In [68]:
col=a[:,np.newaxis]
col.shape

(6, 1)

In [75]:
r=np.random.randint(0,20,(4,5))
r

array([[ 9, 12, 13, 14, 18],
       [ 0, 15,  8,  3, 12],
       [13,  0,  0, 15,  6],
       [ 5,  7,  8,  0,  1]])

In [81]:
r[r>=5]  #giving condition within the index asme as grater_five=r>5

array([ 9, 12, 13, 14, 18, 15,  8, 12, 13, 15,  6,  5,  7,  8])